/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datamining;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.security.SecureRandom;
import java.text.DecimalFormat;
import java.util.Arrays;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author yaron
 */
public class gui extends javax.swing.JFrame {

    String pathD = null;
    String pathR = null;

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        RollNum = new javax.swing.JTextField();
        RollB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RouletteNum = new javax.swing.JTextField();
        Spin = new javax.swing.JButton();
        analyzeDice = new javax.swing.JButton();
        analyzeR = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        errorT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DiceResultT = new javax.swing.JTextField();
        RouletteResultT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        browseB = new javax.swing.JButton();
        chooseT = new javax.swing.JTextField();
        sequenceDice = new javax.swing.JButton();
        sequenceRoulette = new javax.swing.JButton();
        longestDice = new javax.swing.JTextField();
        longestRoulette = new javax.swing.JTextField();
        longestDResult = new javax.swing.JTextField();
        longestRResult = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        browseB1 = new javax.swing.JButton();
        chooseT1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("ANALYZER"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        jLabel1.setText("Roll the Dice");

        RollNum.setText("10000");
        RollNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollNumActionPerformed(evt);
            }
        });

        RollB.setText("Roll");
        RollB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollBActionPerformed(evt);
            }
        });

        jLabel2.setText("Spin the Roulette");

        RouletteNum.setText("10000");
        RouletteNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RouletteNumActionPerformed(evt);
            }
        });

        Spin.setText("Spin");
        Spin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpinActionPerformed(evt);
            }
        });

        analyzeDice.setText("analyze Dice");
        analyzeDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeDiceActionPerformed(evt);
            }
        });

        analyzeR.setText("analyze Roulette");
        analyzeR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeRActionPerformed(evt);
            }
        });

        jLabel3.setText("Approximation error:");

        errorT.setText("1");
        errorT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorTActionPerformed(evt);
            }
        });

        jLabel4.setText("%");

        DiceResultT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiceResultTActionPerformed(evt);
            }
        });

        jLabel5.setText("Choose file for dice:");

        browseB.setText("browse ");
        browseB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBActionPerformed(evt);
            }
        });

        sequenceDice.setText("longest sequence Dice");
        sequenceDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sequenceDiceActionPerformed(evt);
            }
        });

        sequenceRoulette.setText("longest sequence Roulette");
        sequenceRoulette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sequenceRouletteActionPerformed(evt);
            }
        });

        longestDice.setText("1");

        longestRoulette.setText("1");

        jLabel6.setText("Choose file for roulette:");

        browseB1.setText("browse ");
        browseB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(RollNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RollB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(RouletteNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Spin))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseB)
                        .addGap(28, 28, 28)
                        .addComponent(chooseT, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(analyzeR)
                            .addComponent(analyzeDice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DiceResultT, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RouletteResultT, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sequenceDice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(longestDice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sequenceRoulette)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(longestRoulette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(longestDResult)
                            .addComponent(longestRResult, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(browseB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chooseT1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(RollNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RollB)
                    .addComponent(jLabel5)
                    .addComponent(browseB)
                    .addComponent(chooseT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RouletteNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spin)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(browseB1)
                    .addComponent(chooseT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(errorT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(analyzeDice)
                            .addComponent(DiceResultT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(analyzeR)
                    .addComponent(RouletteResultT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sequenceDice)
                    .addComponent(longestDice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(longestDResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sequenceRoulette)
                    .addComponent(longestRoulette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(longestRResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RollNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RollNumActionPerformed

    private void RouletteNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RouletteNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RouletteNumActionPerformed

    private void RollBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollBActionPerformed
        try {
            DiceResultT.setText("");
            PrintWriter writer = new PrintWriter("Dice.txt");
            int downRow = 0;
            for (int i = 0; i < Integer.parseInt(RollNum.getText()); i++) {
                if (downRow == 100) {
                    writer.println();
                    downRow = 0;
                }
                Random r = new SecureRandom();
                int rand = r.nextInt();
                int x = Math.abs(rand % 6) + 1;
                writer.print(x + ",");
                downRow++;
            }
            writer.close();
        } catch (IOException e) {
            // do something
        }
    }//GEN-LAST:event_RollBActionPerformed

    private void SpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpinActionPerformed
        try {
            RouletteResultT.setText("");
            PrintWriter writer = new PrintWriter("Roulette.txt");
            int downRow = 0;
            for (int i = 0; i < Integer.parseInt(RouletteNum.getText()); i++) {
                if (downRow == 100) {
                    writer.println();
                    downRow = 0;
                }
                writer.print((int) (Math.random() * 37) + ",");
                downRow++;
            }
            writer.close();
        } catch (IOException e) {
            // do something
        }    }//GEN-LAST:event_SpinActionPerformed

    private void analyzeDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeDiceActionPerformed
        try {
            BufferedReader br;
            if (pathD == null) {
                br = new BufferedReader(new FileReader("Dice.txt"));
            } else {
                br = new BufferedReader(new FileReader(pathD));
            }
            try {
                String line;
                int[] count = new int[6];
                while ((line = br.readLine()) != null) {
                    String[] words = line.split(",");
                    for (int i = 0; i < words.length; i++) {
                        int number = Integer.parseInt(words[i]);
                        count[number - 1]++;
                    }
                }
                double[] result = new double[6];
                for (int i = 0; i < count.length; i++) {
                    result[i] = count[i] / Double.parseDouble(RollNum.getText());
                }
                double tohelet = 0;
                for (int i = 0; i < result.length; i++) {
                    tohelet += (result[i] * (i + 1));
                }
                String[] percentage = new String[6];
                for (int i = 0; i < percentage.length; i++) {
                    percentage[i] = String.format("%.3f", result[i]);
                }
                br.close();
                PrintWriter writer = new PrintWriter("Dice Results.txt");
                boolean isFair = true;
                double epsilon = 0.01 * Integer.parseInt(errorT.getText());
                for (int i = 0; i < count.length; i++) {
                    if ((tohelet > 3.5 + epsilon) || (tohelet < 3.5 - epsilon)) {
                        isFair = false;
                    }
                }
                if (isFair) {
                    DiceResultT.setText("the Dice is fair");
                    writer.println("the Dice is fair");
                    writer.println("Distribution of results: (in percentage)" + Arrays.toString(percentage));
                } else {
                    DiceResultT.setText("the Dice isn't fair");
                    writer.println("the Dice isn't fair");
                    writer.println("Distribution of results: (in percentage)" + Arrays.toString(percentage));
                }

                writer.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        } catch (FileNotFoundException e) {
            System.out.println(e);
            //e.printStackTrace();
            System.err.println("Eror: need 'Dice.txt' file");
        }
    }//GEN-LAST:event_analyzeDiceActionPerformed

    private void analyzeRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeRActionPerformed
        try {
            BufferedReader br;
            if (pathR == null) {
                br = new BufferedReader(new FileReader("Roulette.txt"));
            } else {
                br = new BufferedReader(new FileReader(pathR));
            }
            try {
                String line;
                int[] count = new int[37];
                while ((line = br.readLine()) != null) {
                    String[] words = line.split(",");
                    for (int i = 0; i < words.length; i++) {
                        int number = Integer.parseInt(words[i]);
                        count[number]++;
                    }
                }
                br.close();
                PrintWriter writer = new PrintWriter("Roulette Results.txt");
                double[] result = new double[37];
                for (int i = 0; i < count.length; i++) {
                    result[i] = count[i] / Double.parseDouble(RouletteNum.getText());
                }
                double tohelet = 0;
                for (int i = 0; i < result.length; i++) {
                    tohelet += (result[i] * i);
                }
                String[] percentage = new String[37];
                for (int i = 0; i < percentage.length; i++) {
                    percentage[i] = String.format("%.3f", result[i]);
                }
                boolean isFair = true;
                double epsilon = 0.025 * Integer.parseInt(errorT.getText());
                for (int i = 0; i < count.length; i++) {
                    if ((tohelet > 18 + epsilon) || (tohelet < 18 - epsilon)) {
                        isFair = false;
                    }
                }
                if (isFair) {
                    RouletteResultT.setText("the Roulette is fair");
                    writer.println("the Roulette is fair");
                    writer.println("Distribution of results: (in percentage)" + Arrays.toString(percentage));
                } else {
                    RouletteResultT.setText("the Roulette isn't fair");
                    writer.println("the Roulette isn't fair");
                    writer.println("Distribution of results: (in percentage)" + Arrays.toString(percentage));
                }
                writer.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        } catch (FileNotFoundException e) {
            System.out.println(e);
            //e.printStackTrace();
            System.err.println("Eror: need 'Roulette.txt' file");
        }

    }//GEN-LAST:event_analyzeRActionPerformed

    private void errorTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorTActionPerformed

    private void browseBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter fileExtensionFilter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        chooser.setFileFilter(fileExtensionFilter);
        chooser.setDialogTitle("Open");
        int NOTC = chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        if (NOTC == JFileChooser.APPROVE_OPTION) {
            pathD = file.getAbsolutePath();
            chooseT.setText(pathD);
        }
    }//GEN-LAST:event_browseBActionPerformed

    private void DiceResultTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiceResultTActionPerformed

    }//GEN-LAST:event_DiceResultTActionPerformed

    private void sequenceDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sequenceDiceActionPerformed
        try {
            BufferedReader br;
            if (pathD == null) {
                br = new BufferedReader(new FileReader("Dice.txt"));
            } else {
                br = new BufferedReader(new FileReader(pathD));
            }
            String line;
            int count = 0, max = 0;
            while ((line = br.readLine()) != null) {
                String[] words = line.split(",");
                if (Integer.parseInt(words[0]) != Integer.parseInt(longestDice.getText())) {
                    count = 0;
                }
                for (int i = 0; i < words.length; i++) {
                    if (Integer.parseInt(words[i]) == Integer.parseInt(longestDice.getText())) {
                        count++;
                        for (int j = i + 1; j < words.length; j++) {
                            if (Integer.parseInt(words[j]) == Integer.parseInt(longestDice.getText())) {
                                count++;
                                i = j + 1;
                            } else {
                                i = j + 1;
                                max = Math.max(max, count);
                                count = 0;
                                break;
                            }
                        }
                    }
                }
            }
            br.close();
            longestDResult.setText("the longest sequence of " + longestDice.getText() + " is: " + max);

            PrintWriter writer = new PrintWriter(new FileWriter("Dice Results.txt", true));
            writer.append("the longest sequence of " + longestDice.getText() + " is: " + max);
            writer.close();

        } catch (IOException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sequenceDiceActionPerformed

    private void sequenceRouletteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sequenceRouletteActionPerformed
        try {
            BufferedReader br;
            if (pathR == null) {
                br = new BufferedReader(new FileReader("Roulette.txt"));
            } else {
                br = new BufferedReader(new FileReader(pathR));
            }
            String line;
            int count = 0, max = 0;
            while ((line = br.readLine()) != null) {
                String[] words = line.split(",");
                if (Integer.parseInt(words[0]) != Integer.parseInt(longestRoulette.getText())) {
                    count = 0;
                }
                for (int i = 0; i < words.length; i++) {
                    if (Integer.parseInt(words[i]) == Integer.parseInt(longestRoulette.getText())) {
                        count++;
                        for (int j = i + 1; j < words.length; j++) {
                            if (Integer.parseInt(words[j]) == Integer.parseInt(longestRoulette.getText())) {
                                count++;
                                i = j + 1;
                            } else {
                                i = j + 1;
                                max = Math.max(max, count);
                                count = 0;
                                break;
                            }
                        }
                    }
                }
            }
            br.close();
            longestRResult.setText("the longest sequence of " + longestRoulette.getText() + " is: " + max);

            PrintWriter writer = new PrintWriter(new FileWriter("Roulette Results.txt", true));
            writer.append("the longest sequence of " + longestDice.getText() + " is: " + max);
            writer.close();

        } catch (IOException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sequenceRouletteActionPerformed

    private void browseB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseB1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter fileExtensionFilter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        chooser.setFileFilter(fileExtensionFilter);
        chooser.setDialogTitle("Open");
        int NOTC = chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        if (NOTC == JFileChooser.APPROVE_OPTION) {
            pathR = file.getAbsolutePath();
            chooseT1.setText(pathR);
    }//GEN-LAST:event_browseB1ActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DiceResultT;
    private javax.swing.JButton RollB;
    private javax.swing.JTextField RollNum;
    private javax.swing.JTextField RouletteNum;
    private javax.swing.JTextField RouletteResultT;
    private javax.swing.JButton Spin;
    private javax.swing.JButton analyzeDice;
    private javax.swing.JButton analyzeR;
    private javax.swing.JButton browseB;
    private javax.swing.JButton browseB1;
    private javax.swing.JTextField chooseT;
    private javax.swing.JTextField chooseT1;
    private javax.swing.JTextField errorT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField longestDResult;
    private javax.swing.JTextField longestDice;
    private javax.swing.JTextField longestRResult;
    private javax.swing.JTextField longestRoulette;
    private javax.swing.JButton sequenceDice;
    private javax.swing.JButton sequenceRoulette;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
